version: '3'
services:
    app:
        image: kaangiray26/peerjs-server-auth:1.0
        restart: on-failure
        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            version: 1.0
            port: 3000
            NODE_ENV: production 
            POSTGRES_HOST: postgres
            POSTGRES_USER: peerjs
            POSTGRES_PASSWORD: peerjs
            POSTGRES_PORT: 5432
            POSTGRES_DB: peerjs

    postgres:
        image: kaangiray26/postgres:2.0
        restart: always
        environment:
            POSTGRES_USER: peerjs
            POSTGRES_PASSWORD: peerjs
            POSTGRES_DB: peerjs
        volumes:
            - db-metadata:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U peerjs" ]
            interval: 5s
            timeout: 5s
            retries: 10
volumes:
    db-metadata: